[tool:pytest]
addopts = --cov=. --cov-report=html:Tests/htmlcov --cov-report=term -v --tb=short --cov-config=.coveragerc
fail_under = 55
testpaths = Tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*